c = ('Palmeiras', 'Santos', 'Flamengo', 'Internacional', 'Atlético', 'Goiás', 'Botafogo', 'Bahia', 'São Paulo', 'Corinthians', 'Grêmio', 'Athletico-PR', 'Ceará', 'Fortaleza', 'Vasco', 'Fluminense', 'Chapecoense', 'Cruzeiro', 'CSA', 'Avaí')
print('-='*136)
print(f'Lista de times do Brasileirão: {c}')
print('-='*136)
print(f'Os cinco primeiros são {c[0:5]}')
print('-='*136)
print(f'Os 4 últimos são {c[-4:]}')
print('-='*136)
print(f'Os times em ordem alfabética: {sorted(c)}')
print('-='*136)
cp = c.index('Chapecoense')
print(f'O Chapecoense está na {cp+1}ª Posição')